spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gamelove
          jwk-set-uri: http://localhost:8080/realms/gamelove/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
    listener:
      ack-mode: record
      retry:
        enabled: true
        max-attempts: 3
        backoff:
          delay: 1000
    template:
      default-topic: game-events
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
    dlq:
      enabled: true
      topic: game-events-dlt

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

