spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gamelove
          jwk-set-uri: http://localhost:8080/realms/gamelove/protocol/openid-connect/certs